# Generated by Django 3.2.3 on 2021-06-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_domain', models.IntegerField()),
                ('domain_name', models.CharField(max_length=120)),
                ('ip', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'domains',
            },
        ),
    ]
